version: '3'

services:
  db:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - mongo_db:/data/db
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      net:

  auth:
    container_name: auth
    build: ./auth
    depends_on:
      - db
    volumes:
      - ./auth:/app
    ports:
      - '5001:3000'
    environment:
      OAUTH_CALLBACK_URL: x
      OAUTH_CLIENT_SECRET: x
      OAUTH_CLIENT_ID: x
      MONGO_DB_HOST: db
      MONGO_DB_NAME: test
      MONGO_DB_USERNAME: root
      MONGO_DB_PASSWORD: rootpassword
    networks:
      net:

networks:
  net:
    driver: bridge

volumes:
  mongo_db:
  #auth:
  # ulimits:
  #   container_name: ui
  #   build: ./ui
  #   volumes:
  #     - './ui:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
