version: '3'

services:
  db:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017-27019:27017-27019'
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mongo/data/db:/data/db/

  auth:
    container_name: auth
    build: ./auth
    ports:
      - '5000:3000'
    environment:
      OAUTH_SECRET: sercretsecrrretsecret
      OAUTH_USERID: userisueusersdsagsadsa
    depends_on:
      - db
    volumes:
      - ./auth:/app
      - ./shared:/app/shared

  ulimits: :
    container_name: ui
    build: ./ui
    volumes:
      - './ui:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
